core/urls.py
from django.urls import path

from core import views

app_name = 'core'

urlpatterns = [
    path('about/', views.AboutView.as_view(), name='about'),

    path('register/', views.register, name='register'),
    
    path('login/user/', views.user_login, name='user_login'),
    path('logout/user/', views.user_logout, name='user_logout'),
    path('user/<str:pk>/', views.UserDetailView.as_view(), name='user_detail'),
    path('update/user/<str:pk>/', views.UserUpdateView.as_view(), name='user_update'),
    path('delete/user/<str:pk>/', views.UserDeleteView.as_view(), name='user_delete'),

    path('page_list/', views.PageListView.as_view(), name='page_list'),
    path('delete/page/<str:pk>/', views.PageDeleteView.as_view(), name='page_delete'),
    path('update/page/<str:pk>/', views.PageUpdateView.as_view(), name='page_update'),
    path('create/page/', views.PageCreateView.as_view(), name='page_create'),

    path('create/section/page/<str:page_pk>/', views.SectionCreateView.as_view(), name='section_create'),
    path('update/section/<str:pk>/page/<str:page_pk>/', views.SectionUpdateView.as_view(), name='section_update'),
    path('delete/section/<str:pk>/', views.SectionDeleteView.as_view(), name='section_delete'),
    path('updating/', views.update_info, name='update_info'),

    path('create/place/page/<str:page_pk>/', views.PlaceCreateView.as_view(), name='place_create'),
    path('update/place/<str:pk>/page/<str:page_pk>/', views.PlaceUpdateView.as_view(), name='place_update'),
    path('delete/place/<str:pk>/', views.PlaceDeleteView.as_view(), name='place_delete'),
    path('liking/', views.like, name='like'),
  
    path('exploración/', views.ExplorationView.as_view(), name='exploración'),

]

peru/urls.py
from django.contrib import admin
from django.urls import path, include

from core import views

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('admin/', admin.site.urls),
    path('core/', include('core.urls')),
]


# STUFF FOR WHEN I NEED TO DEPLOY THE APP
from django.conf import settings
from django.conf.urls.static import static
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

from django.views.static import serve
from django.urls import re_path

urlpatterns += [
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),]

core/models/page.py
from django.urls import reverse
from django.db.models import Model
from django.db.models.fields import CharField
from django.db.models.fields.files import ImageField

class Page(Model):
    map = ImageField(upload_to='section_pics')

    periods = ['Incas', 'Colonial', 'Monarquía del Perú', 'Independencia', 'Presente']
    tuple_periods = [(c, c) for c in periods]
    period = CharField(max_length=64, choices=tuple_periods)
    
    categories = ['Historia', 'Costumbres', 'Lugares']
    tuple_categories = [(c, c) for c in categories]
    category = CharField(max_length=64, choices=tuple_categories)

    def get_absolute_url(self):
        return reverse(f"core:exploración") + f"?period={self.period}&category={self.category}"

core/models/place.py

from django.urls import reverse
from django.db.models import Model, CASCADE
from django.db.models.fields import CharField, TextField, IntegerField
from django.db.models.fields.files import ImageField
from django.db.models.fields.related import ForeignKey

class Place(Model):
    name = CharField(max_length=64)
    description = TextField(max_length=8192)
    image = ImageField(upload_to='place_pics')
    likes = IntegerField(default=0)

    page = ForeignKey('Page', on_delete=CASCADE, related_name="places")

    def get_absolute_url(self):
        return reverse("core:exploración") + f"?period={self.page.period}&category={self.page.category}"

core/models/section.py

from django.urls import reverse
from django.db.models import Model, CASCADE
from django.db.models.fields import CharField, TextField, IntegerField
from django.db.models.fields.files import ImageField
from django.db.models.fields.related import ForeignKey

class Section(Model):
    title = CharField(max_length=64)
    content = TextField(max_length=8192)
    image = ImageField(upload_to='section_pics')
    order = IntegerField(unique=True)

    page = ForeignKey('Page', on_delete=CASCADE, related_name="sections")

    def get_absolute_url(self):
        return reverse("core:exploración") + f"?period={self.page.period}&category={self.page.category}"

core/models/user.py

from django.contrib.auth.models import User
from django.urls import reverse

class UserProfile(User):
    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse(f"core:user_detail", kwargs={"pk": self.pk})

core/forms.py
"""Forms used by models that do not have a CreateView or UpdateView
All forms use the crispy_forms django app, including the ones in CreateViews or UpdateViews
crispy_forms: https://django-crispy-forms.readthedocs.io/en/latest/
"""

from django import forms
from core.models import UserProfile

class UserProfileForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = UserProfile
        fields = ['username', 'password']

core/views/index.py
"""The most basic views"""

from typing import Any, Dict
from django.views.generic import TemplateView
from django.shortcuts import render
from ..models.page import Page

class IndexView(TemplateView):
    template_name = 'core/index.html'

class ExplorationView(TemplateView):
    template_name = 'core/page/exploración.html'

class AboutView(TemplateView):
    template_name = 'core/about.html'

core/views/like.py
from django.http import JsonResponse

from ..models.place import Place

def like(request):
    place = Place.objects.get(pk=request.GET.get('place'))
    place.likes += 1
    place.save()
    data = {'likes': place.likes}
    return JsonResponse(data)

core/views/page.py
from typing import Any, Dict, List
from django.db.models.query import QuerySet

from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.contrib import messages
from django.views.generic import CreateView
from django.views.generic import ListView, UpdateView, DeleteView, CreateView

from core.mixins import IsSuperuserMixin
from core.models import Page

class PageListView(ListView):
    model = Page
    template_name = 'core/page/list.html'

    def get(self, request: HttpResponse,
        *args: (Any),
        **kwargs: Dict[str, Any]) -> HttpResponse:
        
        """Gets the link to the appropriate view
        Redirects user to the PageListView or if there is
        only one Page object in the QuerySet object,
        redirects to that Page's DetailView
        Saves the user time
        """
        
        queryset = self.get_queryset()
        if queryset and len(queryset) == 1:
            messages.warning(request,
                'This is the only page that matches your search.')
            
            page = queryset.first()
            return HttpResponseRedirect(reverse('core:exploración') + f"?period={page.period}&category={page.category}")

        if len(queryset) == self.model.objects.all().count() and "search" in request.GET:
            messages.warning(request,
                'Nothing matches your search.')

        return super().get(request, *args, **kwargs)

    def get_queryset(self) -> QuerySet:
        """Gets all the Thing objects to be displayed
        Returns only the Thing objects that fit
        the filters in the request's querystring
        """

        search_querysets = []
        if 'search' in self.request.GET:
            query = self.request.GET['search']
            for page in self.model.objects.all():
                for section in page.sections.all():
                    if query in section.content or query in section.title:
                        search_querysets.append(self.model.objects.all().filter(pk=page.pk))
                        break

                for place in page.places.all():
                    if query in place.name or query in place.description:
                        search_querysets.append(self.model.objects.all().filter(pk=page.pk))
                        break

        if len(search_querysets) == 0:
            return self.model.objects.all();

        queryset = self.combine(search_querysets)
        return queryset

    @staticmethod
    def combine(queryset: List) -> QuerySet:
        """Used to combine QuerySet objects in a list of QuerySet objects"""

        final_queryset = queryset[0]
        for query in queryset[1:]:
            final_queryset |= query

        return final_queryset

class PageDeleteView(IsSuperuserMixin, DeleteView):
    login_url = 'core:user_login'
    model = Page
    success_url = reverse_lazy("core:page_list")
    template_name = 'core/page/confirm_delete.html'

class PageUpdateView(IsSuperuserMixin, UpdateView):
    login_url = 'core:user_login'
    fields = ['map', 'period', 'category']
    model = Page
    template_name = 'core/page/form.html'

class PageCreateView(IsSuperuserMixin, CreateView):
    login_url = 'core:user_login'
    fields = ['map', 'period', 'category']
    model = Page
    template_name = 'core/page/create.html'

core/views/place.py
"""Views associated with Place objects"""

from django.forms import Form
from django.http import HttpResponse

from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, DeleteView

from core.models import Page, Place
from core.mixins import IsSuperuserMixin

class PlaceCreateView(IsSuperuserMixin, CreateView):
    login_url = 'core:user_login'
    fields = ['name', 'description', 'image']
    model = Place
    template_name = 'core/place/form.html'

    def form_valid(self, form: Form) -> HttpResponse:
        """Manually sets the page for a place
        Page comes from the request
        """

        page = Page.objects.get(pk=int(self.kwargs['page_pk']))        
        form.instance.page = page
        return super().form_valid(form)

class PlaceUpdateView(IsSuperuserMixin, UpdateView):
    login_url = 'core:user_login'
    fields = ['name', 'description', 'image']
    model = Place
    template_name = 'core/place/form.html'

class PlaceDeleteView(IsSuperuserMixin, DeleteView):
    login_url = 'core:user_login'
    model = Place
    template_name = 'core/place/confirm_delete.html'

    def get_success_url(self) -> HttpResponse:
        """Redirects the user back to the Page's detail view they deleted the place from"""

        page = self.get_object().page
        return reverse_lazy(f"core:exploración") + f"?period={page.period}&category={page.category}"

core/views/section.py
"""Views associated with Section objects"""

from django.forms import Form
from django.http import HttpResponse

from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, DeleteView

from core.models import Page, Section
from core.mixins import IsSuperuserMixin

class SectionCreateView(IsSuperuserMixin, CreateView):
    login_url = 'core:user_login'
    fields = ['title', 'content', 'image', 'order']
    model = Section
    template_name = 'core/section/form.html'

    def form_valid(self, form: Form) -> HttpResponse:
        """Manually sets the page for a section
        Page comes from the request
        """

        page = Page.objects.get(pk=int(self.kwargs['page_pk']))        
        form.instance.page = page
        return super().form_valid(form)

class SectionUpdateView(IsSuperuserMixin, UpdateView):
    login_url = 'core:user_login'
    fields = ['title', 'content', 'image', 'order']
    model = Section
    template_name = 'core/section/form.html'

class SectionDeleteView(IsSuperuserMixin, DeleteView):
    login_url = 'core:user_login'
    model = Section
    template_name = 'core/section/confirm_delete.html'

    def get_success_url(self) -> HttpResponse:
        """Redirects the user back to the Page's detail view they deleted the section from"""

        page = self.get_object().page
        return reverse_lazy(f"core:exploración") + f"?period={page.period}&category={page.category}"

core/views/update_info.py
from django.http import JsonResponse
from django.urls import reverse_lazy

from ..models.page import Page

def update_info(request):
    period = request.GET.get('period', 'Incas')
    category = request.GET.get('category', 'Historia')
    page = Page.objects.get(period=period, category=category)

    data = {
        'period': page.period,
        'category': page.category,
        'map': f"{page.map.url}",
        'section': f"{reverse_lazy('core:section_create', kwargs={'page_pk': page.pk})}",
        'place': f"{reverse_lazy('core:place_create', kwargs={'page_pk': page.pk})}",
        'update': f"{reverse_lazy('core:page_update', kwargs={'pk': page.pk})}",
        
        'sections': [page.sections.count(),
            [(section.title,
              reverse_lazy('core:section_update', kwargs={'pk': section.pk, 'page_pk': page.pk}),
              section.content,
              section.image.url) for section in page.sections.order_by('order')]],
        
        'places': [page.places.count(),
            [(place.name,
              reverse_lazy('core:place_update', kwargs={'pk': place.pk, 'page_pk': page.pk}),
              place.description,
              place.image.url,
              place.pk,
              place.likes) for place in page.places.all()]],
              
    }

    return JsonResponse(data)

core/views/user.py
"""Views associated with a UserProfile object"""

from django.shortcuts import render

from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required
from django.views.generic import DetailView, UpdateView, DeleteView

from core.models import UserProfile
from core.forms import UserProfileForm
from core.mixins import LoginRequiredMixin, IsTheUserMixin

@login_required()
def user_logout(request: HttpResponse) -> HttpResponse:
    """View to logout user
    Redirects user to index page
    """

    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request: HttpResponse) -> HttpResponse:
    """View used to register a user
    Redirects user to index page or if there is a next URL parameter, redirects user to appropriate page
    """
    
    registered = False

    if request.method == 'POST':
        user_form = UserProfileForm(data=request.POST)

        if user_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            
            if not user.first_name:
                user.first_name = user.username.capitalize()

            if not user.last_name:
                user.last_name = 'User'

            user.save()

            registered = True
            messages.success(request, "Thank you for registering, now login to begin experiencing Minas Gerais.")

    else:
        user_form = UserProfileForm()

    if registered:
        next_page = request.GET.get('next')
        if next_page:
            return HttpResponseRedirect(reverse('core:user_login') + f'?next={next_page}')

        return HttpResponseRedirect(reverse('core:user_login'))

    else:
        return render(request,
            'core/user/registration.html',
            {'user_form': user_form,})

def user_login(request: HttpResponse) -> HttpResponse:
    """View used to login a user
    Redirects user to index page or if there is a next URL parameter, redirects user to appropriate page
    """
    
    next_page = request.GET.get('next')

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                if next_page:
                    return HttpResponseRedirect(next_page)
            
                return HttpResponseRedirect(reverse('index'))

            else:
                messages.error(request,'Account not active')

        else:
            messages.error(request,'Invalid credentials')
        
    else:
        if next_page:
            messages.warning(request, 'Login is required for that action')

    return render(request, 'core/user/login.html')

class UserDetailView(LoginRequiredMixin, DetailView):
    """View to see a user's profile"""
    
    login_url = 'core:user_login'
    context_object_name = "user_detail"
    model = UserProfile
    template_name = 'core/user/detail.html'

class UserUpdateView(IsTheUserMixin, UpdateView):
    """View to update a UserProfile object"""
    
    login_url = 'core:user_login'
    fields = ['username']
    model = UserProfile
    template_name = 'core/user/form.html'

    def form_valid(self, form):
        return super().form_valid(form)

class UserDeleteView(IsTheUserMixin, DeleteView):
    """View to delete a UserProfile object"""

    login_url = 'core:user_login'
    model = UserProfile
    template_name = 'core/user/confirm_delete.html'
    success_url = reverse_lazy("index")

core/templates/core/base/base.html
<!DOCTYPE html>
<html lang="en" class='h-100'>
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <script src="https://code.jquery.com/jquery-3.1.1.min.js" integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="{% static 'core/js/main.js' %}"></script>

    <link rel="stylesheet" type="text/css" href="{% static 'core/css/bootstrap.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'core/css/starability-basic.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'core/css/main.css' %}"/>
</head>

<body class="d-flex flex-column h-100">
    {% for message in messages %}
    <div class="position-fixed bottom-0 end-0 p-3" style="z-index: 11">
        <div class="toast {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
            text-white bg-success
            {% elif message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
            text-white bg-danger
            {% elif message.level == DEFAULT_MESSAGE_LEVELS.WARNING %}
            bg-warning
            {% endif %}" id="liveToast" role="alert"aria-live="assertive" aria-atomic="true">
            
            <div class="toast-header">
                <strong class="me-auto">Peru Exploración</strong>
                <small>Just Now</small>
                <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
            </div>
            
            <div class="toast-body">
                {{message}}
            </div>
        </div>
    </div>
    {% endfor %}

    <main class="flex-shrink-0">
        <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
            <div class="container-fluid">
                <a class="navbar-brand" href="{%url 'index'%}">Peru Exploración</a>
                
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        {% if user.is_superuser %}
                        <li class="nav-item">
                            <a class="nav-link" href="{%url 'admin:index'%}">Admin</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{%url 'core:page_create'%}">Create Page</a>
                        </li>
                        {% endif %}                        
                    </ul>

                    <div class="d-flex">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        {% if user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link" href="{%url 'core:user_logout'%}">Logout</a>
                            </li>
                        {% endif %}
                            <li class="nav-item">
                                <a class="nav-link" href="{%url 'core:about'%}">About</a>
                            </li>
                        </ul>

                        <form action="{% url "core:page_list" %}"class="d-flex">
                            <input name="search" class="form-control me-2" list="datalistOptions" type="search" placeholder="Search" aria-label="Search">
                            <button class="btn btn-outline-success" type="submit">Search</button>
                        </form>

                    </div>
                </div>
            </div>
        </nav>
    </main>
      
    <div class="container py-4 mt-5">
        {% block base_body %}
        {% endblock base_body %}
    </div>

    <footer class="footer mt-auto py-3">
        <span class="text-muted">
            <ul class="nav justify-content-center border-bottom pb-3 mb-3">
                <li class="nav-item"><a href="https://github.com/GoldV2/peru" class="nav-link px-2 text-muted">Code</a></li>
                <li class="nav-item"><a href="{% url 'core:about' %}" class="nav-link px-2 text-muted">About</a></li>
            </ul>
            
            <p class="text-center text-muted">A-7/8 Spanish III 2021-2022</p>
        </span>
    </footer>

</body>
</html>

core/templates/core/base/confirm_delete.html
{% extends 'core/base/base.html' %}

{% block base_body %}

<div class="p-4 mb-2 bg-light rounded-3">
{% block delete_body %}
{% endblock delete_body %}
</div>    

{% block delete_extra %}
{% endblock delete_extra %}

<form method="POST">
    {% csrf_token %}
    <input class="btn btn-danger" type="submit" value="Delete">
    {% block cancel_button %}
    {% endblock cancel_button %}
</form>

{% endblock base_body %}

core/templates/core/base/form.html
{% extends 'core/base/base.html' %}

{% block base_body %}

<div class="p-4 mb-2 bg-light rounded-3">
{% block form_body %}
{% endblock form_body %}
</div>    

<div class="p-4 bg-light rounded-3 mb-4">
    <form method="post" enctype='multipart/form-data'>
        {% csrf_token %}

        {% block form_fields %}
        {% endblock form_fields %}
        
        {{ form.as_p }}
        <input type="submit", class='mt-2 btn btn-success', value='Submit'>
    </form>
</div>    

{% endblock base_body %}