core/urls.py
from django.urls import path

from core import views

app_name = 'core'

urlpatterns = [
    path('about/', views.AboutView.as_view(), name='about'),

    path('register/', views.register, name='register'),
    
    path('login/user/', views.user_login, name='user_login'),
    path('logout/user/', views.user_logout, name='user_logout'),
    path('user/<str:pk>/', views.UserDetailView.as_view(), name='user_detail'),
    path('update/user/<str:pk>/', views.UserUpdateView.as_view(), name='user_update'),
    path('delete/user/<str:pk>/', views.UserDeleteView.as_view(), name='user_delete'),

    path('page_list/', views.PageListView.as_view(), name='page_list'),
    path('delete/page/<str:pk>/', views.PageDeleteView.as_view(), name='page_delete'),
    path('update/page/<str:pk>/', views.PageUpdateView.as_view(), name='page_update'),
    path('create/page/', views.PageCreateView.as_view(), name='page_create'),

    path('create/section/page/<str:page_pk>/', views.SectionCreateView.as_view(), name='section_create'),
    path('update/section/<str:pk>/page/<str:page_pk>/', views.SectionUpdateView.as_view(), name='section_update'),
    path('delete/section/<str:pk>/', views.SectionDeleteView.as_view(), name='section_delete'),
    path('updating/', views.update_info, name='update_info'),

    path('create/place/page/<str:page_pk>/', views.PlaceCreateView.as_view(), name='place_create'),
    path('update/place/<str:pk>/page/<str:page_pk>/', views.PlaceUpdateView.as_view(), name='place_update'),
    path('delete/place/<str:pk>/', views.PlaceDeleteView.as_view(), name='place_delete'),
    path('liking/', views.like, name='like'),
  
    path('exploración/', views.ExplorationView.as_view(), name='exploración'),

]

peru/urls.py
from django.contrib import admin
from django.urls import path, include

from core import views

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('admin/', admin.site.urls),
    path('core/', include('core.urls')),
]


# STUFF FOR WHEN I NEED TO DEPLOY THE APP
from django.conf import settings
from django.conf.urls.static import static
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

from django.views.static import serve
from django.urls import re_path

urlpatterns += [
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),]

core/models/page.py
from django.urls import reverse
from django.db.models import Model
from django.db.models.fields import CharField
from django.db.models.fields.files import ImageField

class Page(Model):
    map = ImageField(upload_to='section_pics')

    periods = ['Incas', 'Colonial', 'Monarquía del Perú', 'Independencia', 'Presente']
    tuple_periods = [(c, c) for c in periods]
    period = CharField(max_length=64, choices=tuple_periods)
    
    categories = ['Historia', 'Costumbres', 'Lugares']
    tuple_categories = [(c, c) for c in categories]
    category = CharField(max_length=64, choices=tuple_categories)

    def get_absolute_url(self):
        return reverse(f"core:exploración") + f"?period={self.period}&category={self.category}"

core/models/place.py

from django.urls import reverse
from django.db.models import Model, CASCADE
from django.db.models.fields import CharField, TextField, IntegerField
from django.db.models.fields.files import ImageField
from django.db.models.fields.related import ForeignKey

class Place(Model):
    name = CharField(max_length=64)
    description = TextField(max_length=8192)
    image = ImageField(upload_to='place_pics')
    likes = IntegerField(default=0)

    page = ForeignKey('Page', on_delete=CASCADE, related_name="places")

    def get_absolute_url(self):
        return reverse("core:exploración") + f"?period={self.page.period}&category={self.page.category}"

core/models/section.py

from django.urls import reverse
from django.db.models import Model, CASCADE
from django.db.models.fields import CharField, TextField, IntegerField
from django.db.models.fields.files import ImageField
from django.db.models.fields.related import ForeignKey

class Section(Model):
    title = CharField(max_length=64)
    content = TextField(max_length=8192)
    image = ImageField(upload_to='section_pics')
    order = IntegerField(unique=True)

    page = ForeignKey('Page', on_delete=CASCADE, related_name="sections")

    def get_absolute_url(self):
        return reverse("core:exploración") + f"?period={self.page.period}&category={self.page.category}"

core/models/user.py

from django.contrib.auth.models import User
from django.urls import reverse

class UserProfile(User):
    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse(f"core:user_detail", kwargs={"pk": self.pk})

core/forms.py
"""Forms used by models that do not have a CreateView or UpdateView
All forms use the crispy_forms django app, including the ones in CreateViews or UpdateViews
crispy_forms: https://django-crispy-forms.readthedocs.io/en/latest/
"""

from django import forms
from core.models import UserProfile

class UserProfileForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = UserProfile
        fields = ['username', 'password']

core/views/index.py
"""The most basic views"""

from typing import Any, Dict
from django.views.generic import TemplateView
from django.shortcuts import render
from ..models.page import Page

class IndexView(TemplateView):
    template_name = 'core/index.html'

class ExplorationView(TemplateView):
    template_name = 'core/page/exploración.html'

class AboutView(TemplateView):
    template_name = 'core/about.html'

core/views/like.py
from django.http import JsonResponse

from ..models.place import Place

def like(request):
    place = Place.objects.get(pk=request.GET.get('place'))
    place.likes += 1
    place.save()
    data = {'likes': place.likes}
    return JsonResponse(data)

core/views/page.py
from typing import Any, Dict, List
from django.db.models.query import QuerySet

from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.contrib import messages
from django.views.generic import CreateView
from django.views.generic import ListView, UpdateView, DeleteView, CreateView

from core.mixins import IsSuperuserMixin
from core.models import Page

class PageListView(ListView):
    model = Page
    template_name = 'core/page/list.html'

    def get(self, request: HttpResponse,
        *args: (Any),
        **kwargs: Dict[str, Any]) -> HttpResponse:
        
        """Gets the link to the appropriate view
        Redirects user to the PageListView or if there is
        only one Page object in the QuerySet object,
        redirects to that Page's DetailView
        Saves the user time
        """
        
        queryset = self.get_queryset()
        if queryset and len(queryset) == 1:
            messages.warning(request,
                'This is the only page that matches your search.')
            
            page = queryset.first()
            return HttpResponseRedirect(reverse('core:exploración') + f"?period={page.period}&category={page.category}")

        if len(queryset) == self.model.objects.all().count() and "search" in request.GET:
            messages.warning(request,
                'Nothing matches your search.')

        return super().get(request, *args, **kwargs)

    def get_queryset(self) -> QuerySet:
        """Gets all the Thing objects to be displayed
        Returns only the Thing objects that fit
        the filters in the request's querystring
        """

        search_querysets = []
        if 'search' in self.request.GET:
            query = self.request.GET['search']
            for page in self.model.objects.all():
                for section in page.sections.all():
                    if query in section.content or query in section.title:
                        search_querysets.append(self.model.objects.all().filter(pk=page.pk))
                        break

                for place in page.places.all():
                    if query in place.name or query in place.description:
                        search_querysets.append(self.model.objects.all().filter(pk=page.pk))
                        break

        if len(search_querysets) == 0:
            return self.model.objects.all();

        queryset = self.combine(search_querysets)
        return queryset

    @staticmethod
    def combine(queryset: List) -> QuerySet:
        """Used to combine QuerySet objects in a list of QuerySet objects"""

        final_queryset = queryset[0]
        for query in queryset[1:]:
            final_queryset |= query

        return final_queryset

class PageDeleteView(IsSuperuserMixin, DeleteView):
    login_url = 'core:user_login'
    model = Page
    success_url = reverse_lazy("core:page_list")
    template_name = 'core/page/confirm_delete.html'

class PageUpdateView(IsSuperuserMixin, UpdateView):
    login_url = 'core:user_login'
    fields = ['map', 'period', 'category']
    model = Page
    template_name = 'core/page/form.html'

class PageCreateView(IsSuperuserMixin, CreateView):
    login_url = 'core:user_login'
    fields = ['map', 'period', 'category']
    model = Page
    template_name = 'core/page/create.html'

core/views/place.py
"""Views associated with Place objects"""

from django.forms import Form
from django.http import HttpResponse

from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, DeleteView

from core.models import Page, Place
from core.mixins import IsSuperuserMixin

class PlaceCreateView(IsSuperuserMixin, CreateView):
    login_url = 'core:user_login'
    fields = ['name', 'description', 'image']
    model = Place
    template_name = 'core/place/form.html'

    def form_valid(self, form: Form) -> HttpResponse:
        """Manually sets the page for a place
        Page comes from the request
        """

        page = Page.objects.get(pk=int(self.kwargs['page_pk']))        
        form.instance.page = page
        return super().form_valid(form)

class PlaceUpdateView(IsSuperuserMixin, UpdateView):
    login_url = 'core:user_login'
    fields = ['name', 'description', 'image']
    model = Place
    template_name = 'core/place/form.html'

class PlaceDeleteView(IsSuperuserMixin, DeleteView):
    login_url = 'core:user_login'
    model = Place
    template_name = 'core/place/confirm_delete.html'

    def get_success_url(self) -> HttpResponse:
        """Redirects the user back to the Page's detail view they deleted the place from"""

        page = self.get_object().page
        return reverse_lazy(f"core:exploración") + f"?period={page.period}&category={page.category}"

core/views/section.py
"""Views associated with Section objects"""

from django.forms import Form
from django.http import HttpResponse

from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, DeleteView

from core.models import Page, Section
from core.mixins import IsSuperuserMixin

class SectionCreateView(IsSuperuserMixin, CreateView):
    login_url = 'core:user_login'
    fields = ['title', 'content', 'image', 'order']
    model = Section
    template_name = 'core/section/form.html'

    def form_valid(self, form: Form) -> HttpResponse:
        """Manually sets the page for a section
        Page comes from the request
        """

        page = Page.objects.get(pk=int(self.kwargs['page_pk']))        
        form.instance.page = page
        return super().form_valid(form)

class SectionUpdateView(IsSuperuserMixin, UpdateView):
    login_url = 'core:user_login'
    fields = ['title', 'content', 'image', 'order']
    model = Section
    template_name = 'core/section/form.html'

class SectionDeleteView(IsSuperuserMixin, DeleteView):
    login_url = 'core:user_login'
    model = Section
    template_name = 'core/section/confirm_delete.html'

    def get_success_url(self) -> HttpResponse:
        """Redirects the user back to the Page's detail view they deleted the section from"""

        page = self.get_object().page
        return reverse_lazy(f"core:exploración") + f"?period={page.period}&category={page.category}"

core/views/update_info.py
from django.http import JsonResponse
from django.urls import reverse_lazy

from ..models.page import Page

def update_info(request):
    period = request.GET.get('period', 'Incas')
    category = request.GET.get('category', 'Historia')
    page = Page.objects.get(period=period, category=category)

    data = {
        'period': page.period,
        'category': page.category,
        'map': f"{page.map.url}",
        'section': f"{reverse_lazy('core:section_create', kwargs={'page_pk': page.pk})}",
        'place': f"{reverse_lazy('core:place_create', kwargs={'page_pk': page.pk})}",
        'update': f"{reverse_lazy('core:page_update', kwargs={'pk': page.pk})}",
        
        'sections': [page.sections.count(),
            [(section.title,
              reverse_lazy('core:section_update', kwargs={'pk': section.pk, 'page_pk': page.pk}),
              section.content,
              section.image.url) for section in page.sections.order_by('order')]],
        
        'places': [page.places.count(),
            [(place.name,
              reverse_lazy('core:place_update', kwargs={'pk': place.pk, 'page_pk': page.pk}),
              place.description,
              place.image.url,
              place.pk,
              place.likes) for place in page.places.all()]],
              
    }

    return JsonResponse(data)

core/views/user.py
"""Views associated with a UserProfile object"""

from django.shortcuts import render

from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required
from django.views.generic import DetailView, UpdateView, DeleteView

from core.models import UserProfile
from core.forms import UserProfileForm
from core.mixins import LoginRequiredMixin, IsTheUserMixin

@login_required()
def user_logout(request: HttpResponse) -> HttpResponse:
    """View to logout user
    Redirects user to index page
    """

    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request: HttpResponse) -> HttpResponse:
    """View used to register a user
    Redirects user to index page or if there is a next URL parameter, redirects user to appropriate page
    """
    
    registered = False

    if request.method == 'POST':
        user_form = UserProfileForm(data=request.POST)

        if user_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            
            if not user.first_name:
                user.first_name = user.username.capitalize()

            if not user.last_name:
                user.last_name = 'User'

            user.save()

            registered = True
            messages.success(request, "Thank you for registering, now login to begin experiencing Minas Gerais.")

    else:
        user_form = UserProfileForm()

    if registered:
        next_page = request.GET.get('next')
        if next_page:
            return HttpResponseRedirect(reverse('core:user_login') + f'?next={next_page}')

        return HttpResponseRedirect(reverse('core:user_login'))

    else:
        return render(request,
            'core/user/registration.html',
            {'user_form': user_form,})

def user_login(request: HttpResponse) -> HttpResponse:
    """View used to login a user
    Redirects user to index page or if there is a next URL parameter, redirects user to appropriate page
    """
    
    next_page = request.GET.get('next')

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                if next_page:
                    return HttpResponseRedirect(next_page)
            
                return HttpResponseRedirect(reverse('index'))

            else:
                messages.error(request,'Account not active')

        else:
            messages.error(request,'Invalid credentials')
        
    else:
        if next_page:
            messages.warning(request, 'Login is required for that action')

    return render(request, 'core/user/login.html')

class UserDetailView(LoginRequiredMixin, DetailView):
    """View to see a user's profile"""
    
    login_url = 'core:user_login'
    context_object_name = "user_detail"
    model = UserProfile
    template_name = 'core/user/detail.html'

class UserUpdateView(IsTheUserMixin, UpdateView):
    """View to update a UserProfile object"""
    
    login_url = 'core:user_login'
    fields = ['username']
    model = UserProfile
    template_name = 'core/user/form.html'

    def form_valid(self, form):
        return super().form_valid(form)

class UserDeleteView(IsTheUserMixin, DeleteView):
    """View to delete a UserProfile object"""

    login_url = 'core:user_login'
    model = UserProfile
    template_name = 'core/user/confirm_delete.html'
    success_url = reverse_lazy("index")

core/templates/core/page/confirm_delete.html
{% extends 'core/base/confirm_delete.html' %}

{% block delete_body %}
<h1>Delete "{{page.period}} {{page.category}}"?</h1>
{% endblock delete_body %}

{% block cancel_button %}
<a href="{%url 'core:exploración' %}?period={{ page.period }}&category={{ page.category }}" class="btn btn-success">Cancel</a>
{% endblock cancel_button %}

core/templates/core/page/create.html
{% extends 'core/base/form.html' %}

{% block form_body %}
<h1>Page</h1>
<a href="{% url 'index'%}"><button class="btn btn-warning mb-1" type="button">Cancel</button></a>
{% endblock form_body %}

core/templates/core/page/exploración.html
{% extends 'core/base/base.html' %}

{% load my_filters %}
{% load my_tags %}
{% load static %}

{% block base_body %}
    
{% if user.is_superuser %}
<a id="section" href="" class='btn btn-primary'>Create Section</a>
<a id="place" href="" class='btn btn-primary'>Create Place</a>
<a id="update" href="" class="btn btn-warning mx-1">Update</a>
{% endif %}

<div class="row">
    <div class="col col-12 col-lg-6 mb-2">
        <div class="p-3 text-center bg-light rounded-3">
            <h1 id="periodLabel" for="yearRange" class="display-5 fw-bold"></h1> 
        </div>
    </div>
    <div class="col col-12 col-lg-6 mb-2">
        <div class="p-3 bg-light rounded-3 text-center">
            <input type="radio" value="Historia" class="btn-check" name="options" id="Historia" oninput="updateCategory()">
            <label class="btn btn-outline-dark btn-lg" for="Historia"><h2>Historia</h2></label>            
            <input type="radio" value="Costumbres" class="btn-check" name="options" id="Costumbres" oninput="updateCategory()">
            <label class="btn btn-outline-dark btn-lg" for="Costumbres"><h2>Costumbres</h2></label>
            <input type="radio" value="Lugares" class="btn-check" name="options" id="Lugares" oninput="updateCategory()">
            <label class="btn btn-outline-dark btn-lg" for="Lugares"><h2>Lugares</h2></label>  
        </div>
    </div>
    <div class="row">
        <div class="col col-auto">
            <h3 id="yearLabel" for="yearRange" class=""></h3>
        </div>
        <div class="col">
            <input style="transform: scale(1.5); transform-origin: 0 0; width: 68%;" list="steplist" id="yearRange" type="range" name="rangeInput" value="" min="1438" max="2022" oninput="updatePeriod(this.value)">
            <datalist id="steplist">
            </datalist>
        </div>
    </div>
</div>

<hr class="divider">

<div id="page" style="display: none">

<div class="row">
    <div class="col col-12 col-lg-6 mb-2">
        <img data-toggle="tooltip" title="Presiona el mapa" id="map" src="" class="img-fluid" data-bs-toggle="modal" data-bs-target="#exampleModal">

        <!-- Modal -->
        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered modal-xl">
                <div class="modal-content">
                    <div class="modal-body">
                        <img id="map-modal" src="" style="height: 100%; width: 100%" class="img-fluid">
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col col-12 col-lg-6 mb-2">
        <div id="sections" style="overflow: auto;" data-bs-spy="scroll" data-bs-target="#navbar-example2" data-bs-root-margin="0px 0px -40%" data-bs-smooth-scroll="true" class="scrollspy-example" tabindex="0">
        </div>
    </div>
</div>

</div>

<script>
    searchParams = new URLSearchParams(window.location.search)

    function updateLike(place_pk) {
        $.ajax({
            url: '{% url 'core:like' %}?place=' + place_pk,
            type: 'get',
            success: function(data) {
                $("#place" + place_pk).html(data.likes)
            }
        })
    }
    
    function updateCategory() {
        updatePeriod($("#yearRange").val())
        updateInfo()
    }

    function updateInfo(place_pk) {
        $.ajax({
            url: '{% url 'core:update_info' %}?period=' + $("#periodLabel").html() + "&category=" + $("input[type='radio']:checked").val(),
            type: 'get',
            success: function(data) {
                $("#page").fadeOut(500);

                setTimeout(function() {

                    if ($("#Costumbres").is(":checked")) {
                        $("#steplist").html(
                            `<option>1438</option>
                            <option>1533</option>
                            <option>1879</option>`
                        )                        
                    }
                    
                    else if ($("#Lugares").is(":checked")) {
                        $("#steplist").html(
                            `<option>1438</option>
                            <option>1533</option>
                            <option>1821</option>
                            <option>1879</option>`
                        )                        
                    }

                    else {
                        $("#steplist").html(
                            `<option>1438</option>
                            <option>1533</option>
                            <option>1542</option>
                            <option>1821</option>
                            <option>1879</option>`
                        )   
                    }

                    $('#map').attr("src", data.map)
                    $('#map-modal').attr("src", data.map)
                    $('#section').attr("href", data.section)
                    $('#place').attr("href", data.place)
                    $('#update').attr("href", data.update)
                    
                    $('#sections').empty()
                    for (let i = 0; i < data.sections[0]; i++) {
                        $(`
                            <h2>` + data.sections[1][i][0] + `    </h2>
                            {% if user.is_superuser %}
                            <a href='` + data.sections[1][i][1] + `' type="button" class="btn btn-warning mb-1">Update</a>
                            {% endif %}
                            <p>` + data.sections[1][i][2] + `</p>
                            <img class="img-fluid mx-auto" src="` + data.sections[1][i][3] + `" role="img" preserveAspectRatio="xMidYMid slice">
                        `).appendTo('#sections')

                        if (i != data.sections[0]-1) {
                            $(`<hr class="divider">`).appendTo('#sections')
                        }
                    }
                    
                    for (let i = 0; i < data.places[0]; i++) {
                        $(`
                            <div class="card bg-dark text-white">
                                <img src="` + data.places[1][i][3] + `" class="card-img">
                                <div class="card-img-overlay">
                                <h5 class="card-title">` + data.places[1][i][0] + `</h5>
                                
                                <p class="card-text"><a type="button" class="btn btn-outline-success me-2" onclick="updateLike(` + data.places[1][i][4] + `)">Like</a><small id="place` + data.places[1][i][4] + `" class="">` + data.places[1][i][5] + `</small></p>
                                {% if user.is_superuser %}
                                <a href='` + data.places[1][i][1] + `' type="button" class="btn btn-warning">Update</a>
                                {% endif %}
                                <p class="card-text">` + data.places[1][i][2] + `</p>
                            </div>
                        `).appendTo('#sections')

                        if (i != data.places[0]-1) {
                            $(`<hr class="divider">`).appendTo('#sections')
                        }
                    }
                    
                    setTimeout(function() {
                        resizeScroll()
                    }, 75)

                    $("#page").fadeIn();

                }, 500)

            },
            
            failure: function(data) { 
            }
        })
      }

    function updatePeriod(val) {
        $('#yearLabel').html(val);

        if ($("#Costumbres").is(":checked")) {
            if (1879 <= val) {
                val = "Presente"
            }
            else if (1533 <= val) {
                val = "Colonial"
            }
            else if (1438 <= val) {
                val = "Incas"
            }
        }

        else if ($("#Lugares").is(":checked")) {
            if (1879 <= val) {
                val = "Presente"
            }
            else if (1821 <= val ) {
                val = "Independencia"
            }
            else if (1533 <= val) {
                val = "Colonial"
            }
            else if (1438 <= val) {
                val = "Incas"
            }
        }

        else {
            if (1879 <= val) {
                val = "Presente"
            }
            else if (1821 <= val ) {
                val = "Independencia"
            }
            else if (1542 <= val) {
                val = "Monarquía del Perú"
            }
            else if (1533 <= val) {
                val = "Colonial"
            }
            else if (1438 <= val) {
                val = "Incas"
            }
        }
        
        prev = $('#periodLabel').html()
        if (val != prev) {
            $('#periodLabel').html(val)
            updateInfo()
        } 
    }

    function getYear() {
        years = {"": 1438, "Incas": 1438,
                 "Colonial": 1533, "Monarquía del Perú": 1542,
                 "Independencia": 1821, "Presente": 1879}

        searchParams = new URLSearchParams(window.location.search)
        period = searchParams.get('period')
        updatePeriod(years[period])
        $('#yearRange').val(years[period])
    }

    function getCategory() {
        category = searchParams.get('category')
        if (category == "") {
            $("#Historia").attr("checked", "checked")
        }
        else {
            $("#" + category).attr("checked", "checked")
        }
    }

    function resizeScroll() {
        $("#sections").css("height", $("#map").css("height"))
    }
    
    $(document).ready(function funLoad() {
        $("#page").removeClass("hidden");
        getCategory()
        getYear()
        updateInfo()
    })

    $(window).on('resize', function(){
        resizeScroll();
    });

</script>

{% endblock base_body %}

core/templates/core/page/form.html
{% extends 'core/base/form.html' %}

{% block form_body %}

<h1>Updating {{form.instance.period}} {{form.instance.category}}</h1>
<a href="{%url 'core:exploración' %}?period={{ form.instance.period }}&category={{ form.instance.category }}" class="btn btn-warning">Cancel</a>
<a href="{%url 'core:page_delete' pk=form.instance.pk%}" class="btn btn-danger">Delete</a>

{% endblock form_body %}

core/templates/core/page/list.html
{% extends 'core/base/base.html' %}

{% load my_filters %}
{% load my_tags %}
{% load static %}

{% block base_body %}

<div class="row">
{% if page_list %}
{% for page in page_list %}
<div class="col col-6">
<div class="card mb-3 me-3 p-0" style="max-width: 600px;">
    <div class="row g-0">
        <div class="col-md-4">
        <a href="{%url 'core:exploración' %}?period={{ page.period }}&category={{ page.category }}">
            <img data-toggle="tooltip" title="Presiona el mapa" src="{{ page.map.url }}" class="img-fluid rounded-start" alt="...">
        </a>
        </div>
        
        <div class="col-md-8 my-auto">
            <div class="card-body">
                <ul class="list-group">
                    <a class="list-group-item" aria-current="true">
                        <div class="d-flex w-100 justify-content-between">
                            <h5 class="mb-1">Período</h5>
                        </div>                        
                        <p>{{ page.period }}</p>
                    </a>
                    <a class="list-group-item" aria-current="true">
                        <div class="d-flex w-100 justify-content-between">
                            <h5 class="mb-1">Categoria</h5>
                        </div>                        
                        <p>{{ page.category }}</p>
                    </a>
                </ul>
            </div>
        </div>
    </div>
</div>
</div>
{% endfor %}
{% endif %}
</div>

{% endblock base_body %}